### ISSUE TITLE
value "command" does not work 

### ISSUE THREAD

**Issue by dabela** [brantburnett/jquery.ui.spinner#1]
The value getter / setter does not work. This is broken in the example too (at least on FF and chrome)

$("#myinput").spinner("value")  results in "instance[options].apply is not a function" javascript error

The problem is probably due to "return this.value;" since this seems to be referencing itself but i've never written my own jquery.ui widget so could be wrong and no time to debug..i'm using jquery.ui 1.7.2

I overcame this by writing my own getter in source which is basically a copy of _parseValue since this is what I needed, added the function to getters list and it works.

**Comment by btburnett3** [comment]
Looks like I was foolishly overwriting the function with a local variable.  I've fixed it now.  Thanks.
