### ISSUE TITLE
Doesn't work with ui version 1.8rc3

### ISSUE THREAD

**Issue by myeng4life** [brantburnett/jquery.ui.spinner#2]
I really like this but it doesn't work with 1.8rc3.

I need to use the newer version due to the new button objects included in the ui code.

thanks

**Comment by btburnett3** [comment]
I'm going to be working on updating it for 1.8 very soon

**Comment by myeng4life** [comment]
Thanks,  I look forward to it.
Its amazing this hasn't been incorporated into the Jquery UI.
I have seen many comments about your spinner to possibly be added.
I have been looking at all the spinner widgets and yours is by far the best.
I look forward to the fix.

Thanks

**Comment by bradbirnbaum** [comment]
I'm seeing the same problem on 1.8GA.   Anything you can do to get this working would really be appreciated.

**Comment by ErikWegner** [comment]
+1 for a release working with jquery ui 1.8

**Comment by badsamaritan** [comment]
Someone has posted a fix for jquery ui 1.8 widget factory at http://github.com/jrmey/jquery.ui.spinner.

FYI - The download link doesn't include the updates.

**Comment by ErikWegner** [comment]
jrmey works for me, thanks for the hint

**Comment by btburnett3** [comment]
I've merged back the changes made by jrmey, plus some other tweaks, so the master branch will work with UI 1.8 now.  If anyone needs the 1.7 version, there is a branch at http://github.com/btburnett3/jquery.ui.spinner/tree/UI-1.7 that is compatible with 1.7.  Let me know if you have any problems.

Thanks,
Brant
