### ISSUE TITLE
The up/down buttons are offset in height in ie 8.

### ISSUE THREAD

**Issue by myeng4life** [brantburnett/jquery.ui.spinner#4]
If you notice in Ie 8, the spinner buttons are skewed up by what looks like the height of the input box.

Any idea on how to fix?

**Comment by btburnett3** [comment]
Yes, I've noticed it, but I haven't had time to work on it recently.  If you come up with anything, please let me know.

**Comment by wensting** [comment]
spinner.css
   .ui-spinner {position: relative;border:0px solid white}

**Comment by geriamir** [comment]
add a top: 0px that only IE will see:
spinner.css:
.ui-spinner-buttons
{
    position: absolute;
    t/op: 0px !important;
}

**Comment by justinethier** [comment]
wensting's fix seemed to work for me; I added a pull request for it here: https://github.com/btburnett3/jquery.ui.spinner/pull/9

**Comment by btburnett3** [comment]
Merged in pull request, thanks guys
